// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.28_cac@6.7.14_db0@0.3.4_eslint@10.0.0__ypfahc6ntn4wbyrsgkjfgmzwwu/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.28_cac@6.7.14_db0@0.3.4_eslint@10.0.0__ypfahc6ntn4wbyrsgkjfgmzwwu/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.28_cac@6.7.14_db0@0.3.4_eslint@10.0.0__ypfahc6ntn4wbyrsgkjfgmzwwu/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.28_cac@6.7.14_db0@0.3.4_eslint@10.0.0__ypfahc6ntn4wbyrsgkjfgmzwwu/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.28_cac@6.7.14_db0@0.3.4_eslint@10.0.0__ypfahc6ntn4wbyrsgkjfgmzwwu/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.28_cac@6.7.14_db0@0.3.4_eslint@10.0.0__ypfahc6ntn4wbyrsgkjfgmzwwu/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.28_cac@6.7.14_db0@0.3.4_eslint@10.0.0__ypfahc6ntn4wbyrsgkjfgmzwwu/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.28_cac@6.7.14_db0@0.3.4_eslint@10.0.0__ypfahc6ntn4wbyrsgkjfgmzwwu/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.28_cac@6.7.14_db0@0.3.4_eslint@10.0.0__ypfahc6ntn4wbyrsgkjfgmzwwu/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.28_cac@6.7.14_db0@0.3.4_eslint@10.0.0__ypfahc6ntn4wbyrsgkjfgmzwwu/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.28_cac@6.7.14_db0@0.3.4_eslint@10.0.0__ypfahc6ntn4wbyrsgkjfgmzwwu/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.28_cac@6.7.14_db0@0.3.4_eslint@10.0.0__ypfahc6ntn4wbyrsgkjfgmzwwu/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+devtools@3.2.0_vite@7.3.1_jiti@2.6.1_lightningcss@1.31.1_terser@5.46.0_yaml@2.8.2__vue@3.5.28_typescript@5.9.3_/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+devtools@3.2.0_vite@7.3.1_jiti@2.6.1_lightningcss@1.31.1_terser@5.46.0_yaml@2.8.2__vue@3.5.28_typescript@5.9.3_/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.19.0_@tiptap+core@3.19.0_@tiptap+pm@3.19.0__@tiptap+pm@3._2x7jvt3kovsbvxkesde3ninb3i/node_modules/@nuxt/ui/dist/runtime/plugins/colors.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.5.2/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.5.2/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+icon@2.2.1_magicast@0.5.2_vite@7.3.1_jiti@2.6.1_lightningcss@1.31.1_terser@5.46.0_yaml@_vqmsfa2dwrki745iqmuxp2o7nm/node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.28_cac@6.7.14_db0@0.3.4_eslint@10.0.0__ypfahc6ntn4wbyrsgkjfgmzwwu/node_modules/nuxt/dist/app/plugins/warn.dev.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.28_cac@6.7.14_db0@0.3.4_eslint@10.0.0__ypfahc6ntn4wbyrsgkjfgmzwwu/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | '@nuxt/icon' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
