package seeder

import (
	"butuhbantuan/internal/model/entity"
	"butuhbantuan/pkg/database"
	"fmt"
	"log"

	"github.com/google/uuid"
)

var emergencySeed = []entity.Emergency{
	{
		UUID:             uuid.New(),
		Name:             "Ambulance MPD Peduli",
		OrganizationName: "Yayasan MPD Peduli",
		OrganizationType: "Ambulance",
		EmergencyTypeID:  1,
		Description:      "Layanan ambulans 24 jam di wilayah Sleman.",
		IsVerified:       true,
		OrganizationLogo: "https://res.cloudinary.com/djzrlqubf/image/upload/v1705744433/butuhbantuan/iicqfihmm4uocius8cbe.png",
		Latitude:         "-7.7603593",
		Longitude:        "110.3706952",
		Email:            "mpd@mail.com",
		Phone:            "",
		Whatsapp:         "085327679090",
		DistrictID:       "3404130",
		RegencyID:        "3404",
		ProvinceID:       "34",
		FullAddress:      "Jl. Pogung Dalangan, Pogung Kidul, Sinduadi, Kec. Mlati, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55284",
		TypeOfService:    "Emergency, Transport",
		IsDispatcher:     false,
	},
	{
		UUID:             uuid.New(),
		Name:             "PMI Kab Sleman",
		OrganizationName: "Palang Merah Indonesia",
		OrganizationType: "Ambulance",
		EmergencyTypeID:  1,
		Description:      "Layanan ambulans 24 jam di wilayah Sleman.",
		IsVerified:       true,
		OrganizationLogo: "https://res.cloudinary.com/djzrlqubf/image/upload/v1705744061/butuhbantuan/xteksibif5uschl27nbe.png",
		Latitude:         "-7.7063",
		Longitude:        "110.345",
		Email:            "sleman@pmi.com",
		Phone:            "0274868900",
		Whatsapp:         "085161131368",
		DistrictID:       "3404130",
		RegencyID:        "3304",
		ProvinceID:       "34",
		FullAddress:      "Jl. Dr. Radjiman, Sleman",
		TypeOfService:    "Emergency, Transport",
		IsDispatcher:     false,
	},
	{
		UUID:             uuid.New(),
		Name:             "PMI Kota Yogyakarta",
		OrganizationName: "Palang Merah Indonesia",
		OrganizationType: "Ambulance",
		EmergencyTypeID:  1,
		Description:      "Layanan ambulans 24 jam di wilayah Yogyakarta.",
		IsVerified:       true,
		OrganizationLogo: "https://res.cloudinary.com/djzrlqubf/image/upload/v1705744061/butuhbantuan/xteksibif5uschl27nbe.png",
		Latitude:         "-7.8260963",
		Longitude:        "110.3895176",
		Email:            "pmikota@mail.com",
		Phone:            "0274372176",
		Whatsapp:         "08112979398",
		DistrictID:       "3404130",
		RegencyID:        "3471",
		ProvinceID:       "34",
		FullAddress:      "Jl. Tegal Gendu No.25, Prenggan, Kec. Kotagede, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55172",
		TypeOfService:    "Emergency, Transport",
		IsDispatcher:     false,
	},
	{
		UUID:             uuid.New(),
		Name:             "PMI DIY",
		OrganizationName: "Palang Merah Indonesia",
		OrganizationType: "Ambulance",
		EmergencyTypeID:  1,
		Description:      "Layanan ambulans 24 jam di wilayah DIY.",
		IsVerified:       true,
		OrganizationLogo: "https://res.cloudinary.com/djzrlqubf/image/upload/v1705744061/butuhbantuan/xteksibif5uschl27nbe.png",
		Latitude:         "-7.8009897",
		Longitude:        "110.3892071",
		Email:            "pmidiy@mail.com",
		Phone:            "02745012949",
		Whatsapp:         "02745012949",
		DistrictID:       "3404130",
		RegencyID:        "3404",
		ProvinceID:       "34",
		FullAddress:      "Jl. Siliwangi No.3, RT.09/RW.15, Area Sawah, Banyuraden, Kec. Gamping, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55293",
		TypeOfService:    "Emergency, Transport",
		IsDispatcher:     true,
	},
	{
		UUID:             uuid.New(),
		Name:             "PMI Kab Bantul",
		OrganizationName: "Palang Merah Indonesia",
		OrganizationType: "Ambulance",
		EmergencyTypeID:  1,
		Description:      "Layanan ambulans 24 jam di wilayah Bantul.",
		IsVerified:       true,
		OrganizationLogo: "https://res.cloudinary.com/djzrlqubf/image/upload/v1705744061/butuhbantuan/xteksibif5uschl27nbe.png",
		Latitude:         "-7.8806044",
		Longitude:        "110.329933",
		Email:            "pmibantul@mail.com",
		Phone:            "0274367987",
		Whatsapp:         "08112948118",
		DistrictID:       "3404130",
		RegencyID:        "3402",
		ProvinceID:       "34",
		FullAddress:      "489M+Q2 Bantul, Kabupaten Bantul, Daerah Istimewa Yogyakarta",
		TypeOfService:    "Emergency, Transport",
		IsDispatcher:     false,
	},
	{
		UUID:             uuid.New(),
		Name:             "PMI Kab Gunungkidul",
		OrganizationName: "Palang Merah Indonesia",
		OrganizationType: "Ambulance",
		EmergencyTypeID:  1,
		Description:      "Layanan ambulans 24 jam di wilayah Gunungkidul.",
		IsVerified:       true,
		OrganizationLogo: "https://res.cloudinary.com/djzrlqubf/image/upload/v1705744061/butuhbantuan/xteksibif5uschl27nbe.png",
		Latitude:         "-7.9651913",
		Longitude:        "110.6029701",
		Email:            "pmigk@mail.com",
		Phone:            "0274391244",
		Whatsapp:         "08112653118",
		DistrictID:       "3404130",
		RegencyID:        "3403",
		ProvinceID:       "34",
		FullAddress:      "Jl. Kolonel Sugiyono Jl. Nusa Indah No.3, Gadungsari, Wonosari, Kec. Wonosari, Kabupaten Gunungkidul, Daerah Istimewa Yogyakarta 55812",
		TypeOfService:    "Emergency, Transport",
		IsDispatcher:     false,
	},
	{
		UUID:             uuid.New(),
		Name:             "PMI Kab Kulon Progo",
		OrganizationName: "Palang Merah Indonesia",
		OrganizationType: "Ambulance",
		EmergencyTypeID:  1,
		Description:      "Layanan ambulans 24 jam di wilayah Kulon Progo.",
		IsVerified:       true,
		OrganizationLogo: "https://res.cloudinary.com/djzrlqubf/image/upload/v1705744061/butuhbantuan/xteksibif5uschl27nbe.png",
		Latitude:         "-7.8554211",
		Longitude:        "110.1636751",
		Email:            "pmikp@mail.com",
		Phone:            "02747724533",
		Whatsapp:         "081328861118",
		DistrictID:       "3404130",
		RegencyID:        "3401",
		ProvinceID:       "34",
		FullAddress:      "Jl. Bhayangkara, Serut, Pengasih, Kec. Pengasih, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55652",
		TypeOfService:    "Emergency, Transport",
		IsDispatcher:     false,
	},
	{
		UUID:             uuid.New(),
		Name:             "PSC 119 GES",
		OrganizationName: "Dinkes Kab. Gunungkidul",
		OrganizationType: "Ambulance",
		EmergencyTypeID:  1,
		Description:      "Layanan ambulans 24 jam di wilayah Gunungkidul.",
		IsVerified:       true,
		OrganizationLogo: "https://res.cloudinary.com/djzrlqubf/image/upload/v1705743489/butuhbantuan/p6ldfcxxrjmxvnwjwkin.jpg",
		Latitude:         "-7.9715169",
		Longitude:        "110.5803834",
		Email:            "ges@mail.com",
		Phone:            "119",
		Whatsapp:         "082137137119",
		DistrictID:       "3404130",
		RegencyID:        "3403",
		ProvinceID:       "34",
		FullAddress:      "Besari, Siraman, Kec. Wonosari, Kabupaten Gunungkidul, Daerah Istimewa Yogyakarta 55851",
		TypeOfService:    "Emergency",
		IsDispatcher:     true,
	},
	{
		UUID:             uuid.New(),
		Name:             "PSC 119 Bantul",
		OrganizationName: "Dinkes Kab. Bantul",
		OrganizationType: "Ambulance",
		EmergencyTypeID:  1,
		Description:      "Layanan ambulans 24 jam di wilayah Bantul.",
		IsVerified:       true,
		OrganizationLogo: "https://res.cloudinary.com/djzrlqubf/image/upload/v1705743489/butuhbantuan/p6ldfcxxrjmxvnwjwkin.jpg",
		Latitude:         "-7.9061556",
		Longitude:        "110.3123855",
		Email:            "119bantul@mail.com",
		Phone:            "119",
		Whatsapp:         "02742811119",
		DistrictID:       "3404130",
		RegencyID:        "3402",
		ProvinceID:       "34",
		FullAddress:      "Dagaran, Palbapang, Kec. Bantul, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55713",
		TypeOfService:    "Emergency",
		IsDispatcher:     true,
	},
	{
		UUID:             uuid.New(),
		Name:             "PSC 119 KP",
		OrganizationName: "Dinkes Kab. Kulon Progo",
		OrganizationType: "Ambulance",
		EmergencyTypeID:  1,
		Description:      "Layanan ambulans 24 jam di wilayah Kulon Progo.",
		IsVerified:       true,
		OrganizationLogo: "https://res.cloudinary.com/djzrlqubf/image/upload/v1705743489/butuhbantuan/p6ldfcxxrjmxvnwjwkin.jpg",
		Latitude:         "-7.8592736",
		Longitude:        "110.1536777",
		Email:            "119bantul@mail.com",
		Phone:            "119",
		Whatsapp:         "082258800119",
		DistrictID:       "3404130",
		RegencyID:        "3401",
		ProvinceID:       "34",
		FullAddress:      "Wates, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta",
		TypeOfService:    "Emergency",
		IsDispatcher:     true,
	},
	{
		UUID:             uuid.New(),
		Name:             "PSC 119 SES",
		OrganizationName: "Dinkes Kab. Sleman",
		OrganizationType: "Ambulance",
		EmergencyTypeID:  1,
		Description:      "Layanan ambulans 24 jam di wilayah Sleman.",
		IsVerified:       true,
		OrganizationLogo: "https://res.cloudinary.com/djzrlqubf/image/upload/v1705743489/butuhbantuan/p6ldfcxxrjmxvnwjwkin.jpg",
		Latitude:         "-7.718647",
		Longitude:        "110.35649",
		Email:            "119sleman@mail.com",
		Phone:            "02748609000",
		Whatsapp:         "08112668900",
		DistrictID:       "3404130",
		RegencyID:        "3404",
		ProvinceID:       "34",
		FullAddress:      "79J4+GHX, Beran Kidul, Tridadi, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55511",
		TypeOfService:    "Emergency",
		IsDispatcher:     true,
	},
	{
		UUID:             uuid.New(),
		Name:             "Basarnas Yogyakarta",
		OrganizationName: "Badan Nasional Pencarian dan Pertolongan",
		OrganizationType: "SAR",
		EmergencyTypeID:  3,
		Description:      "Layanan pencarian dan pertolongan wilayah Daerah Istimewa Yogyakarta.",
		IsVerified:       true,
		OrganizationLogo: "https://res.cloudinary.com/djzrlqubf/image/upload/v1749735152/butuhbantuan/Logo_Basarnas_btx5sf.png",
		Latitude:         "-7.8132229",
		Longitude:        "110.2589259",
		Email:            "saryk@mail.com",
		Phone:            "02746498080",
		Whatsapp:         "",
		DistrictID:       "3404130",
		RegencyID:        "3401",
		ProvinceID:       "34",
		FullAddress:      "Jalan Wates Km 11 Sedayu, Ngentak, Argorejo, Bantul, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55752",
		TypeOfService:    "Search and Rescue",
		IsDispatcher:     true,
	},
	{
		UUID:             uuid.New(),
		Name:             "Damkar Sleman",
		OrganizationName: "Pemadan Kebakaran",
		OrganizationType: "Damkar",
		EmergencyTypeID:  2,
		Description:      "Layanan pemadam kebakaran wilayah sleman.",
		IsVerified:       true,
		OrganizationLogo: "https://res.cloudinary.com/djzrlqubf/image/upload/v1749732912/butuhbantuan/LOGO-DAMKAR_lsoh5q.png",
		Latitude:         "-7.717667",
		Longitude:        "110.3504957",
		Email:            "saryk@mail.com",
		Phone:            "0274868351",
		Whatsapp:         "081211311365",
		DistrictID:       "3404130",
		RegencyID:        "3404",
		ProvinceID:       "34",
		FullAddress:      "Jl. Candi Gebang No.3, Beran, Beran Kidul, Tridadi, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55511",
		TypeOfService:    "Kebakaran, Penyelamatan",
		IsDispatcher:     true,
	},
	{
		UUID:             uuid.New(),
		Name:             "Damkar Kota Yogyakarta",
		OrganizationName: "Pemadan Kebakaran",
		OrganizationType: "Damkar",
		EmergencyTypeID:  2,
		Description:      "Layanan pemadam kebakaran wilayah kota yogyakarta.",
		IsVerified:       true,
		OrganizationLogo: "https://res.cloudinary.com/djzrlqubf/image/upload/v1749732912/butuhbantuan/LOGO-DAMKAR_lsoh5q.png",
		Latitude:         "-7.8011184",
		Longitude:        "110.3918975",
		Email:            "damkar@kotajogja.go.id",
		Phone:            "0274587101",
		Whatsapp:         "08112828113",
		DistrictID:       "3404130",
		RegencyID:        "3471",
		ProvinceID:       "34",
		FullAddress:      "Jl. Ipda Tut Harsono, Muja Muju, Kec. Umbulharjo, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55165",
		TypeOfService:    "Kebakaran, Penyelamatan",
		IsDispatcher:     true,
	},
	{
		UUID:             uuid.New(),
		Name:             "Damkar Bantul",
		OrganizationName: "Pemadan Kebakaran",
		OrganizationType: "Damkar",
		EmergencyTypeID:  2,
		Description:      "Layanan pemadam kebakaran wilayah kabupaten bantul.",
		IsVerified:       true,
		OrganizationLogo: "https://res.cloudinary.com/djzrlqubf/image/upload/v1749732912/butuhbantuan/LOGO-DAMKAR_lsoh5q.png",
		Latitude:         "-7.8294871",
		Longitude:        "110.3332521",
		Email:            "damkar@bantulkab.go.id",
		Phone:            "0274368222",
		Whatsapp:         "02746462100",
		DistrictID:       "3404130",
		RegencyID:        "3402",
		ProvinceID:       "34",
		FullAddress:      "Kembaran, Tamantirto, Kec. Kasihan, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55184",
		TypeOfService:    "Kebakaran, Penyelamatan",
		IsDispatcher:     true,
	},
	{
		UUID:             uuid.New(),
		Name:             "Damkar Gunungkidul",
		OrganizationName: "Pemadan Kebakaran",
		OrganizationType: "Damkar",
		EmergencyTypeID:  2,
		Description:      "Layanan pemadam kebakaran wilayah kabupaten gunung kidul.",
		IsVerified:       true,
		OrganizationLogo: "https://res.cloudinary.com/djzrlqubf/image/upload/v1749732912/butuhbantuan/LOGO-DAMKAR_lsoh5q.png",
		Latitude:         "-7.8294871",
		Longitude:        "110.3332521",
		Email:            "damkar@gkkab.go.id",
		Phone:            "0274391113",
		Whatsapp:         "08112657113",
		DistrictID:       "3404130",
		RegencyID:        "3403",
		ProvinceID:       "34",
		FullAddress:      "Besari, Siraman, Kec. Wonosari, Kabupaten Gunungkidul, Daerah Istimewa Yogyakarta 55851",
		TypeOfService:    "Kebakaran, Penyelamatan",
		IsDispatcher:     true,
	},
	{
		UUID:             uuid.New(),
		Name:             "Damkar Kulon Progo",
		OrganizationName: "Pemadan Kebakaran",
		OrganizationType: "Damkar",
		EmergencyTypeID:  2,
		Description:      "Layanan pemadam kebakaran wilayah kabupaten kulon progo.",
		IsVerified:       true,
		OrganizationLogo: "https://res.cloudinary.com/djzrlqubf/image/upload/v1749732912/butuhbantuan/LOGO-DAMKAR_lsoh5q.png",
		Latitude:         "-7.8564098",
		Longitude:        "110.1623972",
		Email:            "damkar@gkkab.go.id",
		Phone:            "0274775113",
		Whatsapp:         "081391126113",
		DistrictID:       "3404130",
		RegencyID:        "3401",
		ProvinceID:       "34",
		FullAddress:      "Jl. Sugiman, Kemiri, Margosari, Kec. Pengasih, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55652",
		TypeOfService:    "Kebakaran, Penyelamatan",
		IsDispatcher:     true,
	},
}

func SeedEmergency() error {

	DB := database.DB

	for _, e := range emergencySeed {
		emergency := e
		migrate := DB.FirstOrCreate(&emergency, entity.Emergency{Name: e.Name})

		if migrate.Error != nil {
			log.Fatal("failed to migrate database", migrate.Error)
		}

		fmt.Println("emergency seeded:", emergency.Name)
	}

	fmt.Println("✅ Emergencies Seeded")

	return nil
}
