const config = {
<<<<<<< HEAD
  API_HOST: process.env.NEXT_PUBLIC_API_HOST,
  MAPBOX_URL: process.env.NEXT_PUBLIC_MAPBOX_URL,
  MAPBOX_API_KEY: process.env.NEXT_PUBLIC_MAPBOX_API_KEY,
  GEOAPIFY_API_KEY: process.env.NEXT_PUBLIC_GEOAPIFY_API_KEY,
  GEOLOCATION_BASE_URL: process.env.NEXT_PUBLIC_GEOLOCATION_BASE_URL,
  BACKEND_HOST: process.env.NEXT_PUBLIC_BACKEND_HOST,
};

export default config;
=======
    API_HOST: process.env.NEXT_PUBLIC_API_HOST,
    MAPBOX_URL: process.env.NEXT_PUBLIC_MAPBOX_URL,
    MAPBOX_API_KEY: process.env.NEXT_PUBLIC_MAPBOX_API_KEY,
    GEOAPIFY_API_KEY: process.env.NEXT_PUBLIC_GEOAPIFY_API_KEY,
    GEOLOCATION_BASE_URL: process.env.NEXT_PUBLIC_GEOLOCATION_BASE_URL,
    BACKEND_HOST: process.env.NEXT_PUBLIC_BACKEND_HOST,
}

export default config
>>>>>>> 6b922f49fc712b0ac112b37d3528c7afe5dd39e0
