#!/bin/bash
# ButuhBantuan — VPS initial setup
# Run once on a fresh Ubuntu 22.04 server as root:
#   sudo bash setup-vps.sh <domain>
#
# Example: sudo bash setup-vps.sh butuhbantuan.id

set -euo pipefail

DOMAIN="${1:?Usage: sudo bash setup-vps.sh <domain>}"
APP_DIR="/opt/butuhbantuan"
BB_USER="bb"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
log()  { echo -e "${GREEN}[setup]${NC} $1"; }
warn() { echo -e "${YELLOW}[warn]${NC}  $1"; }
err()  { echo -e "${RED}[error]${NC} $1"; exit 1; }

[[ $EUID -ne 0 ]] && err "Run as root: sudo bash setup-vps.sh <domain>"

# ── System ────────────────────────────────────────────────────────────────────

log "Updating system..."
apt-get update -qq
apt-get upgrade -y -qq

log "Installing dependencies..."
apt-get install -y -qq \
  curl wget git rsync ufw fail2ban \
  nginx certbot python3-certbot-nginx \
  mysql-server

# ── Node.js 20 ────────────────────────────────────────────────────────────────

log "Installing Node.js 20..."
curl -fsSL https://deb.nodesource.com/setup_20.x | bash - > /dev/null
apt-get install -y -qq nodejs
npm install -g pnpm > /dev/null

# ── User ──────────────────────────────────────────────────────────────────────

log "Creating user '$BB_USER'..."
if ! id -u "$BB_USER" &>/dev/null; then
  useradd -m -s /bin/bash "$BB_USER"
fi

# Allow bb to restart its own services without password
echo "$BB_USER ALL=(ALL) NOPASSWD: /bin/systemctl restart bb-api, /bin/systemctl restart bb-dashboard" \
  > /etc/sudoers.d/bb-services
chmod 440 /etc/sudoers.d/bb-services

# SSH directory for GitHub Actions deploy key
mkdir -p /home/$BB_USER/.ssh
chmod 700 /home/$BB_USER/.ssh
chown -R $BB_USER:$BB_USER /home/$BB_USER/.ssh

# ── Directory structure ───────────────────────────────────────────────────────

log "Creating app directories..."
mkdir -p \
  "$APP_DIR/api/bin" \
  "$APP_DIR/dashboard" \
  "$APP_DIR/web-app/dist" \
  "$APP_DIR/uploads"
chown -R $BB_USER:$BB_USER "$APP_DIR"

# ── MySQL ─────────────────────────────────────────────────────────────────────

log "Configuring MySQL..."
DB_PASS=$(openssl rand -hex 20)

mysql -e "CREATE DATABASE IF NOT EXISTS butuhbantuan
          CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
mysql -e "CREATE USER IF NOT EXISTS '$BB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';"
mysql -e "GRANT ALL PRIVILEGES ON butuhbantuan.* TO '$BB_USER'@'localhost';"
mysql -e "FLUSH PRIVILEGES;"

# Tuning for 2 GB RAM server
cat > /etc/mysql/conf.d/butuhbantuan.cnf << 'EOF'
[mysqld]
innodb_buffer_pool_size = 256M
max_connections         = 100
slow_query_log          = 1
slow_query_log_file     = /var/log/mysql/slow.log
long_query_time         = 2
EOF
systemctl restart mysql

# Write DB credentials hint
cat > "$APP_DIR/api/.env.example" << EOF
# Generated by setup-vps.sh — copy to .env and fill in the blanks
DB_HOST=localhost
DB_PORT=3306
DB_NAME=butuhbantuan
DB_USER=$BB_USER
DB_PASS=$DB_PASS

API_PORT=3001
ADMIN_API_KEY=

MAPBOX_TOKEN=
OSRM_BASE_URL=

UPLOAD_DIR=$APP_DIR/uploads
EOF
chown $BB_USER:$BB_USER "$APP_DIR/api/.env.example"

warn "MySQL password: $DB_PASS  (also saved to $APP_DIR/api/.env.example)"

# ── Nginx ─────────────────────────────────────────────────────────────────────

log "Configuring Nginx..."
rm -f /etc/nginx/sites-enabled/default

# Copy config (generated below)
NGINX_CONF="/etc/nginx/sites-available/butuhbantuan"

cat > "$NGINX_CONF" << NGINX
# ButuhBantuan — Nginx config
# Subdomains:
#   api.$DOMAIN        → Go API          (port 3001)
#   app.$DOMAIN        → Web-app static  (file)
#   dashboard.$DOMAIN  → Dashboard SSR   (port 3002)

# ── API ──────────────────────────────────────────────────────────────────────
server {
    listen 80;
    server_name api.$DOMAIN;

    location / {
        proxy_pass         http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;

        # SSE — must disable buffering
        proxy_buffering    off;
        proxy_cache        off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_set_header   Connection        '';
    }
}

# ── Web-app (static) ─────────────────────────────────────────────────────────
server {
    listen 80;
    server_name app.$DOMAIN;

    root $APP_DIR/web-app/dist;

    gzip            on;
    gzip_types      text/plain text/css application/json application/javascript
                    text/xml application/xml image/svg+xml;
    gzip_min_length 1024;

    location / {
        try_files \$uri \$uri/ /index.html;
    }

    # Cache static assets aggressively
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}

# ── Dashboard (SSR) ──────────────────────────────────────────────────────────
server {
    listen 80;
    server_name dashboard.$DOMAIN;

    location / {
        proxy_pass         http://127.0.0.1:3002;
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_set_header   Upgrade           \$http_upgrade;
        proxy_set_header   Connection        'upgrade';
    }
}
NGINX

ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/butuhbantuan
nginx -t
systemctl reload nginx

# ── Systemd services ─────────────────────────────────────────────────────────

log "Creating systemd services..."

cat > /etc/systemd/system/bb-api.service << EOF
[Unit]
Description=ButuhBantuan API
After=network.target mysql.service
Wants=mysql.service

[Service]
Type=simple
User=$BB_USER
WorkingDirectory=$APP_DIR/api
EnvironmentFile=$APP_DIR/api/.env
ExecStart=$APP_DIR/api/bin/server
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=bb-api

[Install]
WantedBy=multi-user.target
EOF

cat > /etc/systemd/system/bb-dashboard.service << EOF
[Unit]
Description=ButuhBantuan Dashboard
After=network.target

[Service]
Type=simple
User=$BB_USER
WorkingDirectory=$APP_DIR/dashboard
ExecStart=/usr/bin/node .output/server/index.mjs
Environment=PORT=3002
Environment=NODE_ENV=production
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=bb-dashboard

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable bb-api bb-dashboard

# ── Firewall ──────────────────────────────────────────────────────────────────

log "Configuring firewall..."
ufw --force reset > /dev/null
ufw default deny incoming > /dev/null
ufw default allow outgoing > /dev/null
ufw allow ssh > /dev/null
ufw allow 'Nginx Full' > /dev/null
ufw --force enable > /dev/null

# ── fail2ban ─────────────────────────────────────────────────────────────────

log "Enabling fail2ban..."
systemctl enable --now fail2ban > /dev/null

# ── Done ─────────────────────────────────────────────────────────────────────

echo ""
log "✅ Setup complete!"
echo ""
warn "Next steps:"
warn "1. Add deploy public key to /home/$BB_USER/.ssh/authorized_keys"
warn "2. Copy $APP_DIR/api/.env.example → $APP_DIR/api/.env and fill in values"
warn "3. Issue SSL: certbot --nginx -d api.$DOMAIN -d app.$DOMAIN -d dashboard.$DOMAIN"
warn "4. Set GitHub secrets: VPS_HOST, VPS_USER=bb, VPS_SSH_KEY"
